### ISSUE TITLE
Consistent ours/their/self/other terminology

### ISSUE THREAD

**Issue by D4nte** [comit-network/thor#26]
We use both ours/their and self/other terminology.
Instead, we should stick one way to denotate our artifacts vs the other party's artifact.

We should also review the usage of alice/bob/a/b.
I would prefer to steer away from `a` and `b`.
Regarding `alice`/`bob`, I think our usage is mostly fine. Alice being the one that does the first action in a given protocol.

**Comment by luckysori** [comment]
> We use both ours/their and self/other terminology.
Instead, we should stick one way to denotate our artifacts vs the other party's artifact.

I actually don't think this is too relevant. We almost exclusively use `_self` and `_other`, always as suffixes. We only ever use `ours` and `theirs` for the `thor::Balance` struct (not as a suffix), because one cannot use `self` to name a field since it's a Rust keyword.

If we were mixing in `_ours` and `_theirs` suffixes I would understand the need to take action, but that's not the case here.
